---
# handlers file for nginx-site-manage
- import_tasks: reload.yml
  when: not nginxsites_handlers_disabled

- import_tasks: restart.yml
  when: not nginxsites_handlers_disabled

- import_tasks: start.yml
  when: not nginxsites_handlers_disabled

- import_tasks: stop.yml
  when: not nginxsites_handlers_disabled

# vim: et:sw=2:syntax=yaml:ts=2:
